#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1221007158                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : mailto:assobluebuddy@gmail.com                                       # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Fight Anorexia and Bulimia

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Asso BlueBuddy                            
your_link                                 : mailto:assobluebuddy@gmail.com          
your_city                                 : Paris                                
email_address                             : assobluebuddy@gmail.com
facebook_username                         : BluebuddyTCA                                        
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Food Journal
    description                           : Display you food intakes in realtime through the day to get back to your rythm, and to an healthy and balanced alimentation
    fontawesome_icon_name                 : book
    
  - title                                 : Goals
    description                           : Get better by creating goals in various domains like social, alimentation or daily life
    fontawesome_icon_name                 : trophy

  - title                                 : Resources
    description                           : Get help in difficult situations, accurate medical and nutritional data, efficient strategies and resources to get better
    fontawesome_icon_name                 : wrench


# Theme Settings
topbar_color                              : "#278fb7"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/legumes.jpg                   
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#eeeeee"

link_color                                : "#278fb7"

app_title_color                           : "#278fb7"
app_price_color                           : "#278fb7"
app_description_color                     : "#278fb7"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#278fb7"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#278fb7"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#278fb7"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
